version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: teslo-postgres-prod
    restart: always
    environment:
      POSTGRES_DB: teslo_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - teslo-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: teslo-backend-prod
    restart: always
    ports:
      - '3002:3002'
    environment:
      DATABASE_URL: 'postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/teslo_shop?schema=public'
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: '24h'
      PORT: 3002
      NODE_ENV: production
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
    depends_on:
      - postgres
    networks:
      - teslo-network

volumes:
  postgres_data_prod:

networks:
  teslo-network:
    driver: bridge
